repos:
  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.17.5
    hooks:
      - id: pylint
        args: ["src/"]
  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["src/"]
