repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--line-length=88"]
        language_version: python3

  - repo: https://github.com/PyCQA/isort
    rev: 5.15.4
    hooks:
      - id: isort

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.275"
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.17.5
    hooks:
      - id: pylint
        args: ["--rcfile=./.pylintrc", "src/"]
