repos:
  - repo: local
    hooks:
      - id: black
        name: black (local)
        entry: python -m black --line-length=88
        language: system
        files: '\.py$'
      - id: isort
        name: isort (local)
        entry: python -m isort
        language: system
        files: '\.py$'
      - id: ruff
        name: ruff (local)
        entry: python -m ruff check --fix
        language: system
        files: '\.py$'
      - id: pylint
        name: pylint (local)
        entry: python -m pylint --rcfile=./.pylintrc src/
        language: system
        types: [python]
